#!/bin/bash
set -e

# Pre-remove script
if [ "$1" = "remove" ]; then
    if command -v systemctl >/dev/null 2>&1; then
        systemctl stop osec >/dev/null 2>&1 || true
        systemctl stop agent_manager >/dev/null 2>&1 || true
    else
        service agent_manager stop >/dev/null 2>&1 || true
        service osec stop >/dev/null 2>&1 || true
    fi
fi
