[package]
name = "linux-agent"
description = "A Rust crate for sending HTTP POST requests with JSON payloads, parsing configuration files, and communicating with the Linux kernel using Netlink."
authors = [ "zebra. <zebra@gmail.com>"]
#repository = "https://github.com/zebra/linux-agent"
homepage = "https://stalw.art"

keywords = ["post-request", "json", "configuration", "parsing", "netlink", "kernel-communication"]
categories = ["network-programming", "data-processing", "system"]
license = "MIT"
repository = "https://github.com/yourname/json-netlink-handler"
version = "0.10.6"
edition = "2021"
resolver = "2"
[[bin]]
name = "MagicArmor_0"
path = "src/main.rs"

[features]
default = ["ebpf"]
ebpf = ["dep:ebpf_backend"]

[dependencies]
tokio = { version = "1", features = ["full"] }
openssl-sys = { version = "0.9", features = ["vendored"] } # 关键修复点
openssl = {version = "0.10.33", features = ["vendored"]}
#nix = { version = "0.27", features = ["signal"] }
#libc = "0.2"
libc = { version = "0.2", features = ["extra_traits"] }
#scopeguard = "1.2"
#hostinfo = { path =  "../hostinfo" }
online = { path =  "../online" }
task = { path =  "../task" }
common = { path = "../common" }
config = { path = "../config" }
kernel_event =  { path = "../kernel_event" }
reporter = {path = "../reporter"}
logging = { path = "../logging" }
log = "0.4"
netlink = { path = "../netlink" }
udisk = { path = "../udisk"}
kernel_module = { path = "../kernel_module" }
docker = { path = "../docker"}
virus_scan_grpc = { path = "../virus_scan_grpc" }
net_client = { path = "../net_client" }
grpc_gateway = { path = "../grpc_gateway" }
agent_local_svc = { path = "../agent_local_svc" }
ebpf_backend = { path = "../ebpf_backend", optional = true }
local_store = { path = "../local_store" }
process_mgr = { path = "../process_mgr" }
tonic = "0.14"
prost = "0.14"
#[CKlibm]
#libc ="/home/zebra/workspace/rustprj/linux_agent_rust_v10/lib/libc.so.6"
#libm ="/home/zebra/workspace/rustprj/linux_agent_rust_v10/lib/libm.so.6"



