[package]
name = "common"
version = "0.10.6"
edition = "2021"
resolver = "2"

[dependencies]
#ring = { version = "0.17" }
tokio = { version = "1.23", features = ["net", "macros"] }
#tokio-rustls = { version = "0.26", default-features = false, features = ["ring", "tls12"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["tls12"] }
arc-swap = "1.6.0"
configparser = "3.1.0"  # 选择适合的版本
config = { path = "../config" }
pattern = { path = "../pattern" }
