#!/bin/bash

# 初始化环境变量
if [[ ":$LD_LIBRARY_PATH:" != *:/opt/osec/* ]]; then
    export LD_LIBRARY_PATH="/opt/osec/:$LD_LIBRARY_PATH"
fi

while true; do
    # 检查MagicArmor_0进程
    if ! pgrep -f "MagicArmor_0" > /dev/null; then

        /opt/osec/MagicArmor_0 >/dev/null 2>&1 &
        echo "[$(date)] MagicArmor_0 started"
    fi

    # 检查MagicArmor_cli进程
    if ! pgrep -f "MagicArmorAgent" > /dev/null; then
        /opt/osec/MagicArmorAgent >/dev/null 2>&1 &
        echo "[$(date)] MagicArmorAgent started"
    fi

    sleep 10
done

