#!/bin/bash

# 初始化环境变量
if [[ ":$LD_LIBRARY_PATH:" != *:/opt/osec/* ]]; then
    export LD_LIBRARY_PATH="/opt/osec/:$LD_LIBRARY_PATH"
fi

while true; do
    # 检查 magicarmor_0 进程
    if ! ps -ef | grep "MagicArmor_0" | grep -v grep | grep -q .; then
      	/opt/osec/MagicArmor_0 > /dev/null 2>&1 &
     	echo "[$(date)] MagicArmor_0 started"
    fi

   # 检查 magicarmor_agent 进程
    if ! ps -ef | grep "MagicArmorAgent" | grep -v grep | grep -q .; then
      /opt/osec/MagicArmorAgent > /dev/null 2>&1 &
      echo "[$(date)] MagicArmorAgent started"
    fi
    sleep 10
done

